Data/Text/Lazy.hs, tests/Tests/Properties.hs
In which I attempt to define `repeat`, `cycle`, and `iterate` similarly to how [lazy `ByteString`](http://hackage.haskell.org/package/bytestring-0.10.4.1/docs/Data-ByteString-Lazy.html#g:10) does. I have no idea if this can be fused or inlined more, so I will leave that to someone with more knowledge of high-performance Haskell than me.
=> Implement repeat, cycle, iterate for lazy Texts

Data/Text/Encoding.hs
Fixes https://github.com/bos/text/issues/123
=> Don't leak space when passing the undecoded portion to the next iteration

Data/Text/Show.hs, changelog.md, tests/LiteralRuleTest.hs, tests/Makefile, tests/literal-rule-test.sh, text.cabal
Previously these rewrite rules were quite fragile as they could compete with the `unpack` rule defined in `GHC.Base`. This was tickled by 7.10.2, which happened to rewrite the LHS of rules with other rules (which is itself a bug in GHC). This caused the literal rules to fail to fire, which then resulted in long compilation times and poor code generation.
Unfortunately it took a couple of attempts to get this right. The first attempt moved the rules forward in compilation to phase 2; this did not resolve the issue but this fact was hidden by a silly testing mistake. I then added a proper test of the literal rules to prevent future mistakes and found that moving the rules to simplifier phase 1 resolved the issue. 
See [GHC Trac #10528](https://ghc.haskell.org/trac/ghc/ticket/10528) for …
=> Show: Activate literal rewrite rules in simplifier phase 1

Data/Text.hs, Data/Text/Lazy.hs
Hi,
I would like to add instances for `PrintfArg`, I need them and that seems quite useful to have it directly in the library.
I'm not sure if those instances should be guarded behind a conditional checking on GHC version?
Let me know what you think
Thanks in advance
=> Add `PrintfArg` instances for `Text` (strict and lazy).

.gitignore, Data/Text.hs, Data/Text/Encoding/Error.hs, Data/Text/Internal/Builder.hs, Data/Text/Internal/Builder/Functions.hs, Data/Text/Internal/Read.hs, Data/Text/Lazy.hs, Data/Text/Lazy/Builder/Int.hs, Data/Text/Lazy/Encoding.hs, Data/Text/Lazy/Read.hs, Data/Text/Read.hs
This removes several warnings in `text`, fixes breakage with GHC<7.8, and prepares `text` for GHC HEAD/base-4.9 by defining `Semigroup` instances.
Specifically, `text` is warning free with the following settings:
- `cabal configure -w /opt/ghc/head/bin/ghc --ghc-options='-Wall -Wcompat -Wno-inline-rule-shadowing -Werror'`
- `cabal configure -w /opt/ghc/7.10.3/bin/ghc --ghc-options='-Wall -Werror'`
- `cabal configure -w /opt/ghc/7.8.4/bin/ghc --ghc-options='-Wall -Werror'`
- `cabal configure -w /opt/ghc/7.6.3/bin/ghc --ghc-options='-Wall -Werror'`
- `cabal configure -w /opt/ghc/7.4.2/bin/ghc --ghc-options='-Wall -Werror'`
GHC 7.2 and GHC 7.0 still have warnings about FFI & CType newtypes
=> Prepare `text` for GHC HEAD/8.0

Data/Text.hs, Data/Text/Lazy.hs, tests/Tests/Properties.hs
This commit adds a `takeWhileEnd` function, both for strict and lazy Text, closing #89.
Appropriate QuickCheck tests are also added.
I’ve stick as much as possible to the style of the existing `takeWhile` / `dropWhileEnd` / etc.
I am no low-level Haskell expert though, and they are a couple of things I dumbly copy without fully
understanding what they do:
- in Lazy.hs, I use `{-# INLINE takeWhileEnd #-}` and not `{-# INLINE [1] takeWhileEnd #-}`.
This is similar to the existing `{-# INLINE dropWhileEnd #-}` but unlike most inline declarations which use the `[1]`; I don’t know what is the correct declaration to use here.
- in Text.hs, I have added `{-# RULES …}` by mere copy/pasting; I don’t fully understand this RULES thing.
- in Lazy.hs, I did NOT add `{-# RULES …}` because …
=> Implement takeWhileEnd

Data/Text/Array.hs
It shouldn't hurt to use the type-safe variant here. Moreover, this
unsafeCoerce# usage was responsible for STG lint errors
(GHC Trac #8114).
=> Text.Array: Use unsafeFreezeByteArray# in place of unsafeCoerce#

Data/Text/Internal/Fusion.hs, Data/Text/Internal/Fusion/Common.hs, benchmarks/haskell/Benchmarks.hs, benchmarks/haskell/Benchmarks/Stream.hs
Affected macro benchmarks' improvement range from 2%  to 34%. More details are available in the commit message. 
I have also added corresponding micro benchmarks. Also added strictness annotation for `replicateCharI` args.
This change was motivated by a perf measurement for pure Haskell unicode normalization code that I am working on. While comparing the performance with text-icu normalization I found that just stream/unstream with no other processing in between was taking more time than what text-icu was taking for normalizing English text. Now, with this change stream/unstream is performing better than that.
=> Optimize unstream loop (3x better on micro benchmark)

Data/Text.hs, Data/Text/Internal/Builder.hs
The fragile-rule warnings introduced in GHC 8.0 have pointed out a few more places where the rules in `text` may not fire,
* `Data.Text.length` may be inlined before the `compareLength` rules have a change to fire
* the `compareLength` rules match against class ops
* `Data.Text.Lazy.Builder.Internal.flush` may be inlined before the `flush/flush` rule has a chance to fire
I still need to test this against GHC <8.0 and check for performance regressions.
=> [WIP] Various rule-robustness issues

Data/Text/Encoding.hs, Data/Text/Lazy/Encoding.hs, benchmarks/text-benchmarks.cabal, tests/literal-rule-test.sh, text.cabal
This was previously proposed in #67, which was ultimately rejected due to concerns about requiring the use of `bytestring-builder` in a Haskell Platform release that shipped GHC 7.8. That Haskell Platform has since been released, so I don't think it's a concern anymore.
This PR ensures that `encodeUtf8Builder` is always defined, even on older versions of GHC, by depending on the `bytestring-builder` package if a particularly old version of `bytestring` is being used. This dependency shouldn't be a concern going forward, since even if, say, `text` were to become a GHC dependency, building `text` as part of the GHC build process wouldn't incur a `bytestring-builder` dependency.
A real-world example of where this would be useful is in …
=> Depend on bytestring-builder for API backwards compatibility

Data/Text/Internal/Fusion/Common.hs, tests/Tests/Properties.hs
Function now correctly deals with apostrophes, etc. For example, the “s” in “it’s”, should not be transformed to upper.
=> Improvements to `toTitle` functionality

Data/Text/Lazy/Read.hs, Data/Text/Read.hs
Embarrassingly trivial PR here... docs were saying decimal digit instead of hexadecimal digit.
=> Fix documentation for  Data.Text.Read hexadecimal

tests/Tests/Properties.hs
Ensures that the first letter of each word is not lowercase after
`toTitle` transform. Doesn’t check to ensure that it’s uppercase, as
not all alphabets contain uppercase and lowercase letters.
=> Added additional test for toTitle

Data/Text.hs
see #176 
a separate issue is that Data.Text is not tested with non-ascii chars
to test this diff i created 
```
newtype MyString = MyString String deriving Show
instance Arbitrary MyString where
arbitrary = MyString <$> oneof [listOf (chr `fmap` oneof [choose (0,127), choose (65536, 1114111)])]
shrink (MyString s) = map MyString $ shrink s
```
and used it to generate random strings...
the `t_takeEnd` test showed broken with this change and this diff fixed it
=> fix takeEnd and dropEnd - issue #176

Data/Text/Lazy.hs
It looks like `Data.Text.Lazy.cons` is O(1). This is a documentation change only.
=> Data.Text.Lazy.cons is O(1) rather than O(n)

Data/Text.hs, Data/Text/Lazy.hs, tests/Tests/Properties.hs
Closes #171.
(I don't understand the streaming/fusion side of things well enough to add them, or the inline stages well enough to set a good level, unfortunately. The simple but probably suboptimal Lazy unsnoc is more or less copied from ByteString; I think it makes sense because the operation is inherently slow and you'd probably avoid it in performance-sensitive code anyway.)
=> Add `unsnoc` to Data.Text and Data.Text.Lazy

Data/Text/Encoding.hs
The rationale is that we encode from UTF16 code-units to UTF8, and
to encode a *single* UTF16 code-unit we need at most 3-byte in UTF8.
Wherease 4-byte UTF8 encodings would require surrogate UTF16 pairs.
Fixes #194
=> Use lower upper bound for pre-allocation in `encodeUtf8`

README.markdown
https://github.com/bos/text doesn't exist anymore
it was moved to https://github.com/haskell/text
=> fix github links in README

Data/Text.hs, Data/Text/Internal/Fusion/Common.hs, Data/Text/Internal/Fusion/Size.hs, Data/Text/Internal/Fusion/Types.hs, tests/Tests/Regressions.hs, text.cabal
This fixes a variety of size hint bugs in `text`'s fusion framework. It seems these were introduced when the `Size` type was extended to track both upper and lower bounds in f4fc30cea2a41bd26b6c4445843ba1b3f7d0dde8. These could manifest in a variety of issues similar to #197.
=> Fix usage of size hints

Data/Text/IO.hs
This not being documented has bitten me in the past, causing downtime.
=> Document that Data.Text.IO throws on decoding failure

Data/Text.hs
Added some examples for Data.Text transformation functions. Ref: https://github.com/MaxGabriel/Haskell-Documentation/issues/11.
=> Add examples to Data.Text transformations

Data/Text/IO.hs
This fixes #223 
The termination condition of `Text`'s `hGetContents` was relying on the `EOF` marker being replaced by a single `\r`. This would go wrong when the only decode-able character left in the byte buffer is a single `\r`.
`Text` would then think it reached the `EOF` and would stop reading. This changes the termination condition to just keep reading until it actually reaches an `EOF`.
=> Fix termination condition for file reads.

tests/text-tests.cabal
`text-tests` doesn't build because `Tests.IO` has module name `Main`
`Tests.IO` has a separate build target `text-tests-stdio` and it shouldn't be here
```
File name does not match module name:
Saw: ‘Main’
Expected: ‘Tests.IO’
4 | module Main
|        ^^^^
```
=> fix text-tests.cabal

Data/Text/Internal/Builder.hs
Due to a bug in ghc, some unused imports do not yield warnings.
This commit will remove such unused imports in preparation for
the ghc bug fix (see https://ghc.haskell.org/trac/ghc/ticket/13064).
=> Remove unused imports.

Data/Text.hs, Data/Text/Lazy.hs, Data/Text/Show.hs
in most cases, just updating the docs. More interesting stuff for `takeWhileEnd` and `length`, see the corresponding commits. See #202.
=> Address some of the fusion issues in #202

Data/Text.hs, Data/Text/Lazy.hs, benchmarks/text-benchmarks.cabal, cabal.project, changelog.md, tests/text-tests.cabal, text.cabal, th-tests/LICENSE, th-tests/tests/Lift.hs, th-tests/tests/th-tests.hs, th-tests/th-tests.cabal
These use the existing `Data` instances, and have similar trade-offs.
I've also bumped the version number appropriately, but I don't know if that'd be better done later (e.g., by the release manager near the time of release).
=> Add Lift instances for Text.

Data/Text.hs
instead of using memcpy to copy the text n times,
we double the copied text every iteration, thus calling
the super-fast memcpy only ~log n times (with larger and larger chunks to copy)
=> faster replicate

benchmarks/haskell/Benchmarks.hs, benchmarks/haskell/Benchmarks/Builder.hs, benchmarks/haskell/Benchmarks/Concat.hs, benchmarks/haskell/Benchmarks/DecodeUtf8.hs, benchmarks/haskell/Benchmarks/EncodeUtf8.hs, benchmarks/haskell/Benchmarks/Equality.hs, benchmarks/haskell/Benchmarks/FileRead.hs, benchmarks/haskell/Benchmarks/FoldLines.hs, benchmarks/haskell/Benchmarks/Mul.hs, benchmarks/haskell/Benchmarks/Programs/BigTable.hs, benchmarks/haskell/Benchmarks/Programs/Cut.hs, benchmarks/haskell/Benchmarks/Programs/Fold.hs, benchmarks/haskell/Benchmarks/Programs/Sort.hs, benchmarks/haskell/Benchmarks/Programs/StripTags.hs, benchmarks/haskell/Benchmarks/Programs/Throughput.hs, benchmarks/haskell/Benchmarks/Pure.hs, benchmarks/haskell/Benchmarks/ReadNumbers.hs, benchmarks/haskell/Benchmarks/Replace.hs, benchmarks/haskell/Benchmarks/Search.hs, benchmarks/haskell/Benchmarks/Stream.hs, benchmarks/haskell/Benchmarks/WordFrequencies.hs
if we only need to run a few benchmarks,
e.g. `text-benchmarks Pure/drop/Text+tiny`
it's wasteful to initialize all of them
(and read all the test data in memory - all
the test data is a few hundreds of MB, but
we read it in several tests, as different types,
and most seriously, as String - which turns this
into GBs of memory)
=> use environments to lazily initialize benchmarks

Data/Text.hs, Data/Text/Lazy.hs
`template-haskell-2.16.0.0` adds a `liftTyped` method to `Lift`, which is like `lift` but returning `Q (TExp t)` instead of `Q Exp`. `liftTyped` does not have a default implementation in terms of `lift`, so it must be implemented explicitly in the `Lift Text` instances that `text` defines. The implementations I chose are based off of the general approach taken by `Language.Haskell.TH.Syntax`, such as in this example: https://gitlab.haskell.org/ghc/ghc/blob/4898df1cc25132dc9e2599d4fa4e1bbc9423cda5/libraries/template-haskell/Language/Haskell/TH/Syntax.hs#L716
=> Implement liftTyped in the Lift Text instances

text.cabal
GHC HEAD is planning to bump `template-haskell`'s major version number to 2.17 soon (see
https://gitlab.haskell.org/ghc/ghc/issues/17645) to reflect the [Overloaded Quotations](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0246-overloaded-bracket.rst) proposal being implemented. Before this can happen, `text`'s upper version bounds on `template-haskell` need to be bumped to allow `template-haskell-2.17`, as `text` is a boot library.
I have tested this change against GHC HEAD, and all test cases pass. I cannot forsee any interaction between the changes in the Overloaded Quotations proposal and the `text` library, as the only significant changes involve the types of quoted TH expressions and combinators in the `Language.Haskell.TH.Lib` library (neither of which `text` …
=> Allow building with template-haskell-2.17

text.cabal
GHC 8.10 uses ghc-prim-0.6.1 currently.
=> Bump ghc-prim upper bound

Data/Text/Lazy/Builder/Int.hs, text.cabal
This patch adds support for ghc-bignum package in GHC 8.12: cf https://gitlab.haskell.org/ghc/ghc/-/merge_requests/2231
=> Add support for ghc-bignum package

text.cabal
This is needed for [GHC#18279](https://gitlab.haskell.org/ghc/ghc/issues/18279), which seeks to bump `ghc-prim`'s version number to 0.7.0.0 in order to accommodate `GHC.Tuple.Unit` being renamed to `GHC.Tuple.Solo`. Since `text` does not use `GHC.Tuple.Unit`, it is safe to simply bump `text`'s upper version bounds on `ghc-prim`.
=> Allow building with ghc-prim-0.7.*

src/Data/Text.hs, tests/Tests/Regressions.hs
While profiling some project, the following function turned out to be the largest bottleneck:
```haskell
{-# INLINE slice #-}
-- | Substring from @offset@ to @offset + len@
slice :: Int -> Int -> Text -> Text
slice offset len = T.take len . T.drop offset
```
The direct cause of this bottleneck is fusion. The original `take` and `drop` functions work by calculating a new offset and length. A new view of `Text` can be returned without copying the underlying array. However, the `slice` function is rewritten, and the streaming implementation unnecessarily copies the data. This makes it much slower and more memory consuming.
With `take` and `drop` being fast individually, putting them together should not lead to a substantial decrease in performance.
Add a rewrite rule that specifically …
=> Add rewrite rule to unfuse (text . drop)

src/Data/Text.hs, src/Data/Text/Lazy.hs
Added `T.` prefix to PR #306 (Otherwise one uses `span` and `break` from prelude working on lists / `String`s).
=> Add examples to 'span' and 'break'

src/Data/Text/Internal/Unsafe/Shift.hs
This makes the 9.2 prim changes less invasive. If we don't care about de-optimizing ancient GHCs we can remove this module altogether.
=> Use base-provided unsafe shifts

src/Data/Text.hs, src/Data/Text/Lazy.hs
This PR adds the `elem` combinator to the API.
=> Add `elem` combinator to API

src/Data/Text/Internal/Builder.hs, tests/Tests/Regressions.hs
=> Fix #280 (surrogate code points in Builder)

src/Data/Text/Encoding.hs, src/Data/Text/Foreign.hs, src/Data/Text/Internal/ByteStringCompat.hs, src/Data/Text/Internal/Encoding/Fusion.hs, src/Data/Text/Internal/Functions.hs, src/Data/Text/Internal/Lazy/Encoding/Fusion.hs
It turns out that all uses of `withForeignPtr` can safely use
`unsafeWithForeignPtr`.
I believe that this should resolve the regression noted in
[GHC #19557](https://gitlab.haskell.org/ghc/ghc/-/issues/19557)
although I am still benchmarking
=> Use unsafeWithForeignPtr when available

benchmarks/haskell/Benchmarks.hs, benchmarks/haskell/Benchmarks/DecodeUtf8.hs, benchmarks/haskell/Benchmarks/EncodeUtf8.hs, cbits/cbits.c
This PR is just a collection of SSE2 patches from those PRs:
- decodeLatin1 https://github.com/haskell/text/pull/297
- decodeUtf8 https://github.com/haskell/text/pull/298
- encodeUtf8 https://github.com/haskell/text/pull/300
@phadej please have a look.
=> SSE2 patches for encoding and decoding functions

src/Data/Text/Array.hs, src/Data/Text/Internal.hs, src/Data/Text/Internal/Encoding/Utf8.hs, src/Data/Text/Internal/Fusion/Common.hs, src/Data/Text/Internal/Unsafe/Char.hs, text.cabal
`text` package has a special `developer` flag, which enables certain safety checks such as out-of-bounds assertions. It seems it was unused for a long time, because several tests fail when `developer` is enabled. 
I also took an opportunity to make structure of `Array` and `MArray` independent of `developer` mode. Otherwise one cannot, for instance, use a `developer` build of `text` with `aeson` or any other package, which looks into `Text` internals. The reason to store the length of an underlying `ByteArray` is gone long ago: `sizeOfByteArray#` used to round it to the word size, but since GHC 7.0 it's precise. 
There were also redundant asserts, duplicating `unsafeIndex` and `unsafeWrite`. I cleaned them so that `Data.Text.Array` does not have a conditional export list any longer.
=> Fix developer mode

src/Data/Text/Encoding.hs, src/Data/Text/Lazy/Encoding.hs, tests/Tests/Properties/Transcoding.hs, tests/Tests/QuickCheckUtils.hs, tests/Tests/Regressions.hs
Fixes #330.
I found another issue that's not yet fixed: both strict and lazy `decodeUtf8With` are actually memory unsafe if you use a bad `onErr` argument. We allocate a destination buffer with 2x the number of bytes from the original bytestrings, but by using an `onErr` function which replaces any invalid byte with a `Char` which is a surrogate pair in UTF-16, it possible to blow up the size taken by a `Text` to 4x. In practice, `onErr` is almost always `lenientDecode` though, so perhaps a better solution than allocating more memory is to either hide `decodeUtf8With` or clamp the range of `onErr`.
=> Fix UTF-8 decoding of lazy bytestrings

tests/Tests.hs, tests/Tests/Inspection/Lazy.hs, tests/Tests/Inspection/Strict.hs, text.cabal
100 pipelines for strict and lazy API, which used to fuse in GHC 8.10. 
40 of them do not fuse anymore in GHC 9.0. 
CC @bgamari, is this linked to the performance regression discussed at https://gitlab.haskell.org/ghc/ghc/-/issues/19557?
CC @nomeata, it's a pity that `text` tests have not been using `inspection-testing` earlier.
=> Add inspection tests for fusion

src/Data/Text/Encoding.hs
Addresses #341.
Let me know if I should add any INLINE pragmas or "since" notes in the docs.
=> add some utf8 decoding convenience functions

tests/Tests/Properties/Folds.hs, tests/Tests/Properties/Instances.hs, tests/Tests/Properties/Substrings.hs, tests/Tests/Properties/Text.hs, tests/Tests/Properties/Transcoding.hs, tests/Tests/QuickCheckUtils.hs, text.cabal
This is mostly to replace `forAll` (without `shrink`) with a newtype, supporting shrinking. Shrinking is vital for actionable property testing. I also put an effort into making `t_utf8_err` more friendly, with detailed reporting of counterexamples. I hit some issues in utf8 branch, and it was quite difficult to debug otherwise.
=> Refactor tests

src/Data/Text/Lazy/Encoding.hs
Fixes:
```
libraries/text/src/Data/Text/Lazy/Encoding.hs:62:1: error: [-Wunused-imports, -Werror=unused-imports]
The qualified import of ‘Data.ByteString.Unsafe’ is redundant
except perhaps to import instances from ‘Data.ByteString.Unsafe’
To import instances alone, use: import Data.ByteString.Unsafe()
|
62 | import qualified Data.ByteString.Unsafe as B
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
=> [text-1.2] Fix redundant import 

benchmarks/haskell/Benchmarks/EncodeUtf8.hs, src/Data/Text/Encoding.hs, tests/Tests/Properties/Transcoding.hs
Instead of copying each character separately by using `encodeUtf8BuilderEscaped` we instead resort to memcpy to copy the bytes into the target buffer more efficiently.
This PR is based off similar functions in the ByteString package: 
https://github.com/haskell/bytestring/blob/ba3046d9f5bf5cac1246c39f519b8be7ac11f49c/Data/ByteString/Builder/Internal.hs#L832-L845
https://github.com/haskell/bytestring/blob/ba3046d9f5bf5cac1246c39f519b8be7ac11f49c/Data/ByteString/Builder/Internal.hs#L779-L796
=> Use copyToPointer in encodeUtf8Builder

.github/workflows/haskell-ci.yml, text.cabal
Test also GHC 9.2-rc1 under ubuntu.
Generated automatically with `haskell-ci` from `tested-with: GHC-9.2.0.20210821`.
Successful run at https://github.com/andreasabel/text/runs/3576075282?check_suite_focus=true
=> Haskell-CI for 9.2-rc1

src/Data/Text/Internal/Fusion/CaseMapping.hs
#372 is incomplete: it's important to regenerate mappings using a version of GHC, which supports a respective version of Unicode. GHC 9.2 supports Unicode 14.0, so now case mappings are correct.
=> Regenerate case mappings for Unicode 14.0 with matching GHC 9.2

tests/Tests/QuickCheckUtils.hs
Following up on #386 we can put a `drop` in the `Arbitrary` instance to generalize other tests to check that offsets are handled correctly.
=> Tests: Generate chunks that start in the middle of their buffers

benchmarks/haskell/Benchmarks/DecodeUtf8.hs, src/Data/Text/Encoding.hs, src/Data/Text/Lazy/Encoding.hs, tests/Tests/Properties/Transcoding.hs
With UTF8 representation there is no longer a reason to deprecate `decodeASCII`: all three `decodeASCII`, `decodeLatin1` and `decodeUtf8` have different trade offs. 
For example, `aeson` can benefit from using `decodeASCII`, see https://github.com/haskell/aeson/blob/06114272b1889f27a9833d01747b3372c71bcbc4/src/Data/Aeson/Parser/Internal.hs#L345-L349 and discussion at https://github.com/haskell/aeson/issues/893#issuecomment-974404169.
=> Undeprecate decodeASCII

src/Data/Text/Encoding.hs, tests/Tests/Properties/Transcoding.hs
Discovered this while testing `conduit` with `text-2.0`.
In `text-1.2.5.0`
```
> Data.Text.Encoding.streamDecodeUtf8 (Data.ByteString.pack [0x81]) `seq` ()
*** Exception: Cannot decode byte '\x81': Data.Text.Internal.Encoding.streamDecodeUtf8With: Invalid UTF-8 stream
```
But in `text-2.0`
```
> Data.Text.Encoding.streamDecodeUtf8 (Data.ByteString.pack [0x81]) `seq` ()
()
```
This can be fixed by forcing `txt` in 
https://github.com/haskell/text/blob/922d9cc7c537d55e3be2dba2343ef43e25493ace/src/Data/Text/Encoding.hs#L365-L369
But I decided to fix it in a more principled way by making fields of `Decoding` strict.
=> Make streamDecodeUtf8 stricter

src/Data/Text/Encoding.hs, src/Data/Text/Internal/Encoding/Utf8.hs
Currently when `simdutf` is disabled, we fallback to the slowest mode of operation: decode every byte into code points, then encode each code point back. This is wasteful and extremely (100x) slow. This PR provides two fallback options:
* If [`bytestring-0.11.2.0`](https://hackage.haskell.org/package/bytestring-0.11.2.0) is available, use [`Data.ByteString.isValidUtf8`](https://hackage.haskell.org/package/bytestring-0.11.2.0/docs/Data-ByteString.html#v:isValidUtf8).
* Otherwise use Haskell native implementation, but in validation-only mode, which is 10x faster than native decoding/encoding.
=> Faster fallback options when simdutf is not available

src/Data/Text/Lazy.hs
Closes #351 (the other pragma for `lines` was already removed at some point)
=> Remove INLINE isPrefixOf

text.cabal
They may be typical for clang-based systems, but I'm not sure what
that list is.
Fix #398
Related to https://gitlab.haskell.org/ghc/ghc/-/issues/20870
=> Special-case openbsd c++ libraries

text.cabal
Closes #385. 
@RyanGlScott, could you please take a look?
=> Prohibit unbuildable Windows configurations due to GHC bugs wrt TemplateHaskell and C interaction

text.cabal
The system upgrade necessitates this list to be extended.
A better solution should be in cabal, but for now we have
no choice: https://github.com/haskell/cabal/issues/8007
=> Catch up OpenBSD extra-libraries to Clang 13

.drone.yml, text.cabal
Expected to fail because of known issues with GHC 9.2.1.
=> Use official Docker images for arm64

src/Data/Text.hs, src/Data/Text/Lazy.hs, tests/Tests/Lift.hs
This patch allows the Lift instance to make use of the primitive bytes literals made available since template-haskell 2.16. 
It also adds some extra tests to make sure the instance works correctly with multi codepoint characters.
Let me know if you'd like some changes
=> Make Lift instances more efficient

text.cabal
GHC 9.2.2 features a new flag `-fcheck-prim-bounds`, which validates out-of-bounds access everywhere.
http://downloads.haskell.org/ghc/9.2.2/docs/html/users_guide/9.2.2-notes.html#compiler
=> Enable -fcheck-prim-bounds in developer mode

text.cabal
This PR replaces #422 and fixes compilation for wasm32-wasi.
=> Fix compilation for wasm32-wasi

text.cabal
As of GHC 9.4 we use libc+++ and Clang on Windows.
=> Don't link against libgcc_s on Windows with GHC 9.4 and later

text.cabal
=> Bump template-haskell upper bound

src/Data/Text/Lazy/Read.hs, src/Data/Text/Read.hs
Closes #174. `Reader` is a synonym defined using `IReader` which is internal. But rather than export `IReader` this PR just removes mention of it. This only affects the documentation, removing an arguably unnecessary level of indirection.
=> Unfold definition of Data.Text.Read.Reader

src/Data/Text.hs, src/Data/Text/Lazy.hs, tests/Tests/Properties/Folds.hs
Unlike for lists, `foldr'` is a useful primitive for strict `Text` since we can easily iterate from either end. I discovered that while working on the other PR about `statefulSpan`, which uses `foldr'` in a test. It also turns out that `foldr` is lazier than one might expect, thanks to its implementation via a lazy stream, rather than an eager imperative loop, so that seemed worth documenting.
`foldr` and `foldr'` are thus mostly equivalent *denotationally*, ignoring the strictness differences, but *operationally*, `foldr` starts executing from the left, while `foldr'` starts from the right. `foldr` can short-circuit, whereas `foldr'` has to traverse the whole list, but can do so in a tighter loop.
- `foldr'` can also be defined for lazy `Text` but it's a little more involved.
- Dually, …
=> Add foldr' and document the laziness of foldr

src/Data/Text/Foreign.hs
Like #254, but only adds one function. `peekCString` is basically `fromPtr0`.
=> Add withCString

src/Data/Text.hs, src/Data/Text/Lazy.hs, tests/Tests/Properties/Substrings.hs, tests/Tests/QuickCheckUtils.hs, text.cabal
Closes #178 and #362  
Depends on PR #436
This PR implements `spanM` (span from the left) and `spanEndM`  (span from the right) for both strict and lazy `Text`.
`spanM` is a combination of `span` and `foldr`.
- `spanM`, as its name indicates, generalizes `span`, with a monadic predicate, of type `Char -> m Bool` rather than `Char -> Bool`.
- `spanM` generalizes a short-circuiting `foldr`, by also remembering the location where it stopped so you can easily resume with another search from there.
- `spanM` can also implement `foldl'` with the same space and time efficiency, by making the predicate always `True` and only using the state effect.
I argue these two functions pass the Fairbairn threshold as they provide the ability to safely move back and forth inside a `Text`. As mentioned in …
=> Stateful span

src/Data/Text/Encoding.hs, src/Data/Text/Lazy/Encoding.hs
Resolves #248. The basic idea is to split total/partial functions into explicit sections, and place the total section first. Some comments/questions:
1. I am open to making the warnings on partial functions themselves louder e.g. changing `decodeUtf8`'s current text:
> This is a partial function: it checks that input is a well-formed
UTF-8 sequence and copies buffer or throws an error otherwise.
to (up to bikeshedding):
>  __WARNING__: This is a __partial__ function: it checks that input is a well-formed
UTF-8 sequence and copies buffer or throws an error otherwise.
I don't think the danger can really be overemphasized, given how destructive they have proven to be. And this way people using e.g. HLS can see them on hover even if they are not looking at the module's documentation. But I …
=> Emphasize total functions in Data.Text.Encoding

text.cabal
Starting with the 9.4 release, GHC provides `system-cxx-std-lib`, a
"virtual" package which can be used to reliably link against the
system's C++ standard library implementation.
See GHC #20010.
=> Use system-cxx-std-lib virtual package where available

changelog.md, src/Data/Text.hs, src/Data/Text/Foreign.hs, src/Data/Text/Lazy.hs, text.cabal
As requested by GHC developers, we should release `text-2.0.1` fairly soon.
=> Bump version to 2.0.1

src/Data/Text.hs, src/Data/Text/Lazy.hs, tests/Tests/Properties/Text.hs
=> Speed up toLower

src/Data/Text.hs, src/Data/Text/Internal.hs, src/Data/Text/Show.hs, tests/Tests/Properties/LowLevel.hs
Closes #464. 
What I don't really understand is why in spite of `{-# NOINLINE unpackCStringAscii# #-}` and `{-# NOINLINE unpackCString# #-}` GHC still applies worker-wrapper transformation:
```haskell
-- RHS size: {terms: 1, types: 0, coercions: 0, joins: 0/0}
emojis1857 :: Addr#
emojis1857
= "\\240\\159\\143\\180\\243\\160\\129\\167\\243\\160\\129\\162\\243\\160\\129\\183\\243\\160\\129\\172\\243\\160\\129\\179\\243\\160\\129\\191"#
-- RHS size: {terms: 8, types: 10, coercions: 0, joins: 0/0}
emojis1856 :: Text
emojis1856
= case $wunpackCString# emojis1857 of
{ (# ww1_ahS0, ww2_ahS1, ww3_ahS2 #) ->
Text ww1_ahS0 ww2_ahS1 ww3_ahS2
}
-- RHS size: {terms: 1, types: 0, coercions: 0, joins: 0/0}
emojis1859 :: Addr#
emojis1859 = "wales"#
-- RHS size: {terms: 8, types: 10, coercions: 0, joins: …
```
=> Reduce code bloat for literal strings by avoiding RULES and inlining

.cirrus.yml
Cf. https://github.com/haskell/bytestring/pull/550
=> Fix FreeBSD job

scripts/Arsec.hs, tests/Tests/Properties/Basics.hs, tests/Tests/Properties/LowLevel.hs, tests/Tests/Properties/Substrings.hs, tests/Tests/Properties/Transcoding.hs
CLC has approved the proposal to add `{-# WARNING #-}` to `Data.List.{head,tail}` (https://github.com/haskell/core-libraries-committee/issues/87). It means that usage of `head` and `tail` will emit compile-time warnings.
This patch eliminates `head` and `tail` or quashes the warning by other means.
=> Avoid `Data.List.{head,tail}`

src/Data/Text.hs, src/Data/Text/Internal/Fusion/Common.hs, src/Data/Text/Lazy.hs
Continuing #476. Apparently my grep fu was weak last time.
=> Avoid Data.List.{head,tail} again

src/Data/Text.hs, src/Data/Text/Array.hs, src/Data/Text/Internal/Lazy/Search.hs, src/Data/Text/Internal/Search.hs, src/Data/Text/Show.hs
In some places `text` uses `unsafeDupablePerformIO` which forces allocation of thunk for its result. Most of those cases are for foreign functions which are morally equivalent to C’s `sin` (sine calculation) function in the sense that they’re actually pure.
This PR removes the thunk mentioned by not introducing `IO` in those cases.
Due to some recent-ish fix `unsafeDupablePerformIO` (https://gitlab.haskell.org/ghc/ghc/-/issues/19181) the function now uses `GHC.Magic.lazy` which forces thunk allocation and no optimization will ever make it cease to do so.
For instance, with current implementation of `length` for text the resulting length is always wrapped into a thunk even if demanded strictly.
For example, next is the core of the worker for the function `foo` that takes text’s length. …
=> Declare pure FFI functions as not living in IO

.github/workflows/haskell-ci.yml, cabal.haskell-ci
I typoed the variable name so haddock was never run, and I didn't find a way to have a default value when the variable is unset, so I had to set it for each job.
=> ci: Fix run-haddock flag

text.cabal
This is the version that GHC 9.6 is going to ship with.
See also: https://gitlab.haskell.org/ghc/ghc/-/issues/22767
=> Allow building with template-haskell-2.20.*

src/Data/Text/Internal.hs
The `pack` function converts a `String` to `Text`. It allocates 4 bytes per `Char` into a mutable byte array (as a UTF-8 character will take 4 bytes in the worse case). After all the `Char`s have been written to the byte array, we should shrink the mutable byte array to the actual size required.
This shrinking operation does not seem to be present. This PR adds it. This should lead to substantial memory savings for long `String`s.
Sorry if I've not understood something. Let me know if the `shrinkM` is not required.
=> pack: shrink the backing mutable byte array after 'Chars' have been added

.github/workflows/arm.yml, .github/workflows/emulated.yml
Self-hosted runners are much faster than QEMU emulation, which often hits timeouts.
=> Move ARM jobs to self-hosted runners

cbits/is_ascii.c, src/Data/Text.hs, src/Data/Text/Lazy.hs, tests/Tests/Properties/Folds.hs
Now that `Text`s are represented internally as a UTF-8 bytestring, we can provide a fast `isAscii :: Text -> Bool` that inspects the bytestring directly, rather than `Char` by `Char`. Such a function can come in handy in serialization libraries, and can't easily be written by an end user. Plus, the C snippet already exists, so there's not much to do.
=> add C-based `isAscii :: Text -> Bool`

src/Data/Text/Encoding.hs
Useful function for serialization libs. Currently you have to do something like [this](https://github.com/raehik/binrep/blob/06a609336c25aadd02948aedb2c6f05319050bdb/src/Binrep/Type/Text/Encoding/Ascii.hs#L26-L38), which is nasty and weird for something that isn't really inherently so.
I find the decoding setup to be a little messy and this makes no attempt to improve on that. I wouldn't mind assisting on that work too.
=> add safe decodeASCII'

text.cabal
See https://downloads.haskell.org/ghc/latest/docs/users_guide/debugging.html#ghc-flag--fproc-alignment
Otherwise comparing benchmarks between different versions of GHC could be meaningless because of different cache-line alignment.
=> Set -fproc-alignment=64 for benchmarks

src/Data/Text.hs
Fixed #500.
See https://gitlab.haskell.org/ghc/ghc/-/issues/22886#note_478463 and https://gitlab.haskell.org/ghc/ghc/-/issues/22886#note_479157 for discussion.
=> Eta-expand to{Lower,Upper,CaseFold} to avoid performance regression in GHC 9.6

tests/Tests/Properties/Text.hs
See #501. Let's go with a tactical fix for now, just to keep CI green.
=> Guard t_toCaseFold_char with #if MIN_VERSION_base(4,16,0)

.github/workflows/emulated.yml, src/Data/Text/Array.hs, text.cabal
This is a part of a grand plan to unify `ShortByteString`, `Data.Text.Array` and `Data.Primitive.ByteArray` to share the same data type. If it looks good, I'll make a release of `data-array-byte` package.
=> Switch Data.Text.Array to Data.Array.Byte

cbits/validate_utf8.cpp, src/Data/Text/Internal/PrimCompat.hs, src/Data/Text/Internal/Validate.hs, src/Data/Text/Internal/Validate/Simd.hs, text.cabal
This makes it possible for users to validate ByteArray# when compiling with the SIMDUTF8 flag on. It does not, however, provide any fallbacks for when that flag is off. That is left as future work.
Related to https://github.com/haskell/text/issues/479
=> Expose SIMD UTF-8 validation functions from internal module

src/Data/Text.hs, tests/Tests.hs, tests/Tests/RebindableSyntaxTest.hs, text.cabal
The Lift Int instance produces a polymorphic literal, which desugars to fromIntegral under RebindableSyntax. Fixing that instance in base may be too much of a breaking change if a lot of code relies on the accidental polymorphism. We can at least fix Lift Text by not relying on Lift Int.
Fixes #533
=> Make Lift Text work under RebindableSyntax

cbits/measure_off.c, src/Data/Text.hs, src/Data/Text/Internal/Reverse.hs, text.cabal
CC @hsyl20, @luite , and others whose handles I don't know (Jeff, Josh, ...)
To write programs with the JS backend, text's C bits need to be replaced, either with JavaScript bits or with pure Haskell. Sylvain suggested pure Haskell.
I'm opening this draft just to check if this is the direction you all expected a pure-Haskell implementation to go.
1. Introduce a Cabal flag `pure-haskell`
2. Introduce a CPP guard macro `PURE_HASKELL` that is defined if `pure-haskell` is true.
3. Use the guard to decide whether to use the C bits or write a Haskell implementation.
4. (not implemented) make `pure-haskell` default to True when the target platform is JS.
This method allows one to test the pure-Haskell implementation on the platform of their choice.
As a proof of concept, I have introduced a …
=> Isolate reverse in preparation for a pure-Haskell implementation

src/Data/Text/Internal/Reverse.hs
Looks like these snuck in as part of https://github.com/haskell/text/pull/536
=> Remove accidentally committed dump pragmas

src/Data/Text.hs, src/Data/Text/Internal.hs, src/Data/Text/Internal/Lazy.hs, src/Data/Text/Lazy.hs
This PR adds type synonyms for lazy and strict flavours of `Text`.
closes #317
=> Add type synonyms for lazy and strict text flavours

src/Data/Text.hs, src/Data/Text/Internal/Measure.hs, text.cabal
Implement `measure_off` in pure Haskell for use with the JS backend
=> Implement measure_off in pure Haskell

src/Data/Text.hs, src/Data/Text/Foreign.hs, src/Data/Text/Internal.hs, src/Data/Text/Internal/Lazy.hs, src/Data/Text/Internal/Reverse.hs, src/Data/Text/Internal/Transformation.hs, src/Data/Text/Lazy.hs, src/Data/Text/Show.hs, tests/Tests.hs, tests/Tests/ShareEmpty.hs, text.cabal
This MR ensures that empty Text values are shared.
This required:
- making sure that empty values are NOINLINE.
- In turn inlining cannot optimise length checks for empty text, so, we add a RULE for optimising `null empty` and try to use null more.
- Lazy Text has a separate constructor for empty values. This means we need to be careful with code shared between strict and lazy text that we don't check for emptiness twice or when we can guarantee that they're non-empty.
Resolves #492
=> Share empty Text values

src/Data/Text/Internal/Transformation.hs
The other implementation looks identical:
```haskell
reverseNonEmpty (Text (A.ByteArray ba) off len) = runST $ do
marr@(A.MutableByteArray mba) <- A.new len
unsafeIOToST $ c_reverse mba ba (fromIntegral off) (fromIntegral len)
brr <- A.unsafeFreeze marr
return $ Text brr 0 len
```
=> Reenable -fpure-haskell

src/Data/Text/Internal/Validate.hs, src/Data/Text/Internal/Validate/Native.hs, tests/Tests/Properties.hs, tests/Tests/Properties/Validate.hs, text.cabal
=> Fix `isValidUtf8ByteArray`

src/Data/Text.hs, src/Data/Text/Encoding.hs, src/Data/Text/Internal/IsAscii.hs, text.cabal
wip. Will add some comments inline.
=> Add pure-Haskell replacement for is_ascii.c

src/Data/Text.hs
Avoids allocating intermediate lists. Does not make any change to the algorithm.
Fixes #550.
As mentioned in https://github.com/haskell/text/issues/550#issuecomment-1880244020, `concat` can alternately be implemented using a strategy which makes one pass over the list, filling and growing a buffer. This PR only optimizes the existing implementation and _does not_ change to this strategy.
Output of `cabal run text-benchmarks -- -p '$4 == "concat" && $5 == "Text"' +RTS -T ` with GHC 9.6.3:
<details>
<summary>Before:</summary>
```
All
Pure
tiny
concat
Text: OK
15.5 ns ± 1.3 ns,  79 B  allocated,   0 B  copied,  35 MB peak memory
ascii-small
concat
Text: OK
24.4 μs ± 1.3 μs, 147 KB allocated,  17 B  copied,  62 MB peak memory
ascii
concat
Text: OK
41.1 ms ± 3.5 ms, 136 MB allocated,  15 MB …
```
=> Optimize the implementation of Data.Text.concat

src/Data/Text.hs, src/Data/Text/Internal/ArrayUtils.hs, src/Data/Text/Internal/Lazy/Search.hs, src/Data/Text/Internal/Search.hs, text.cabal
This removes use of utils.c under -fpure-haskell.
(Technically there is still one use site of _hs_text_memcmp2,  but it's guarded by MIN_VERSION_BASE(4,11,0). Thus -fpure-haskell is not compatible with ghc-8.2. I think I'm ok with that.)
This PR will conflict with #545 , so I'll keep this one a draft until that one is finalized. Plus, my use of `toList` is probably dumb, and I'd like to come up with a better way of doing it.
=> Pure-haskell "memchr"

src/Data/Text.hs, src/Data/Text/Lazy.hs, tests/Tests/Regressions.hs
=> Fix filter/filter rules for Text and lazy Text

changelog.md, src/Data/Text/Internal/Encoding.hs, src/Data/Text/Internal/Validate.hs, text.cabal
As urged by @wz1000 at https://gitlab.haskell.org/ghc/ghc/-/issues/24079#note_548327, let's make a release of `text-2.1.1` asap.
=> Prepare text-2.1.1 release

src/Data/Text.hs, src/Data/Text/Lazy.hs, tests/Tests/Properties/Substrings.hs, tests/Tests/ShareEmpty.hs
=> Feature: `initsNE` and `tailsNE`.

.github/workflows/developer-flag.yml, .github/workflows/simdutf-flag-windows.yml, .github/workflows/simdutf-flag.yml, .github/workflows/windows_and_macOS.yml
I saw the deprecation message in the logs. Also visible on the archived repo https://github.com/haskell/actions
=> ci: Use haskell-actions/setup (moved from haskell/actions/setup)

tests/Tests/Properties/Basics.hs, tests/Tests/ShareEmpty.hs
Those new warnings added in GHC 9.8. The uses in the test suite are either safe or explicitly intended to test the error case (via `=^=` in `tests/Tests/Utils.hs`).
Here are the relevant build logs that this PR hides:
```
tests/Tests/ShareEmpty.hs:110:60: warning: [GHC-63394] [-Wx-partial]
Warning:     In the use of ‘head’
(imported from Data.List, but defined in GHC.List):
"This is a partial function, it throws an error on empty lists. Use pattern matching or Data.List.uncons instead. Consider refactoring to use Data.List.NonEmpty."
|
110 |   , testCase "inits _ = [empty, ...]" $ assertPtrEqEmpty $ L.head $ T.inits "123"
|                                                            ^^^^^^
tests/Tests/Properties/Basics.hs:62:21: warning: [GHC-63394] [-Wx-partial]
Warning:     In the use of …
```
=> Disable x-partial warnings in tests (uses of head and tail)

src/Data/Text/Internal/Builder.hs
Closes #549 
The generated Core for `f = "a cat" <> "a dog" <> "a fish" :: Data.Text.Lazy.Builder` is now more reasonable:
```
f = "a cat"#
f1 = unpackCString# f
f2 = "a dog"#
f3 = unpackCString# f2
f4 = "a fish"#
f5 = unpackCString# f4
$wf
= \ @s x ww ww1 ww2 ww3 eta ->
let {
lvl
= \ ds eta1 ->
case ds of { Buffer ww4 ww5 ww6 ww7 ->
$wfromString f5 x ww4 ww5 ww6 ww7 eta1
} } in
$wfromString
f1
((\ eta1 eta2 ->
case eta1 of { Buffer ww4 ww5 ww6 ww7 ->
$wfromString f3 (lvl `cast` <Co:9> :: ...) ww4 ww5 ww6 ww7 eta2
})
`cast` <Co:9> :: ...)
ww
ww1
ww2
ww3
eta
```
=> Make fromString INLINEABLE

src/Data/Text.hs, src/Data/Text/Internal/Fusion/Common.hs, src/Data/Text/Lazy.hs, tests/Tests/Properties/Folds.hs
I haven't added tests or benchmarks yet, because I'm not quite sure how to do it. 
Open questions:
* Can QuickCheck generate monadic functions? 
* And what would be a good benchmark?
* Do we need a strict `foldlM'`?
* Why are the `Data.Text.Internal.Fusion.Common` folds marked `INLINE [0]`?
For motivation, see [this recent stackoverflow question](https://stackoverflow.com/questions/77385819/how-to-convert-text-to-vector-without-extraneous-allocations#77390907). There the problem is to convert a text into a vector of characters, but that requires extraneous allocation if done naively with `unfoldr Text.uncons`. If a `foldlM` function were exposed like I implemented in this PR then you can write it efficiently like this:
```haskell
import Data.Text as T
import qualified Data.Vector.Unboxed …
```
=> Add foldlM

src/Data/Text/Lazy.hs
=> Make splitAt and splitAtWord (internal function) strict

benchmarks/haskell/Benchmarks.hs, benchmarks/haskell/Benchmarks/Micro.hs, src/Data/Text/Lazy.hs, text.cabal
Closes #562
The previous implementation, itself based on an earlier version of `Data.List.inits`, inherited the flaw that accessing the i-th element took quadratic time O(i²). This now takes linear time O(i) as expected.
The current version of `Data.List.inits` uses a banker's queue to obtain good performance when generating very long lists. For lazy text, consisting of a few big chunks, that benefit seems negligible. So I chose a simpler implementation.
Benchmarks included.
Quadratic growth before (the "2k" benchmarks take 4x the time of the "1k" benchmarks):
```
Lazy.inits
last 1k:      OK
9.19 ms ± 475 μs
last 2k:      OK
46.7 ms ± 1.5 ms
map-take1 1k: OK
8.99 ms ± 798 μs
map-take1 2k: OK
47.0 ms ± 1.8 ms
```
Linear growth after (the "2k" benchmarks take twice the time of the "1k" …
=> Improve lazy performance of `Data.Text.Lazy.inits`

src/Data/Text/IO/Utf8.hs
This is not just a stylistic change: it also improves atomicity of `putStrLn` in concurrent environment, when multiple threads attempt to execute it at once. See https://www.snoyman.com/blog/2016/11/haskells-missing-concurrency-basics/
(Now `B.putStrLn` is not perfect either, but that's the problem to solve in `bytestring`)
=> Data.Text.IO.Utf8: use B.putStrLn instead of B.putStr t >> B.putStr "\n"

benchmarks/haskell/Benchmarks.hs, benchmarks/haskell/Benchmarks/FileWrite.hs, text.cabal
=> Added file write benchmarks

tests/Tests/Properties/LowLevel.hs, tests/Tests/QuickCheckUtils.hs, tests/Tests/Utils.hs, text.cabal
Now tests different encodings not just UTF8.
Removed NFData constraint so that Builder can be tested.
Should be pulled before hPutStr and hPutBuilder PRs
=> improve test function write_read

.github/workflows/haskell-ci.yml, text.cabal
Fix can be achieved on Hackage by a metadata edit.
=> Bump dependencies

src/Data/Text/IO.hs
=> Fixed off by one for writeBlocksRaw

src/Data/Text/IO.hs, src/Data/Text/Internal/Fusion.hs, src/Data/Text/Internal/IO.hs, src/Data/Text/Lazy/IO.hs
Fixes #442 and #242. Subsumes #592.
This imitates the behavior in base by making the newline part of the chunk.
=> Make putStrLn more atomic with line or block buffering

src/Data/Text/Foreign.hs, tests/Tests/Properties/LowLevel.hs
=> Data.Text.Foreign: added peekCString

src/Data/Text.hs, src/Data/Text/Lazy.hs
=> Add Data.Text.show and Data.Text.Lazy.show

cbits/aarch64/measure_off.c, text.cabal
Vectorised instructions on ARM are pretty uniform, so I moved the implementation into a self-contained C file. This way all our trickery to detect AVX does not obscure the code.
Benchmarks on my M2 machine:
```
All
Pure
ascii-small
length
cons
Text:     OK
1.07 μs ± 105 ns, 82% less than baseline
LazyText: OK
1.11 μs ± 104 ns, 81% less than baseline
ascii
length
cons
Text:     OK
1.31 ms ±  66 μs, 75% less than baseline
LazyText: OK
1.35 ms ± 124 μs, 74% less than baseline
english
length
cons
Text:     OK
60.7 μs ± 3.9 μs, 82% less than baseline
LazyText: OK
64.4 μs ± 4.0 μs, 81% less than baseline
russian
length
cons
Text:     OK
190  ns ±  13 ns, 81% less than baseline
LazyText: OK
192  ns ±  13 ns, 81% less than baseline
japanese
length
cons
Text:     OK
204  ns ±  13 ns, 81% less than …
```
=> Speed up length on ARM

benchmarks/haskell/Benchmarks/Pure.hs, src/Data/Text.hs, src/Data/Text/Internal/Transformation.hs, src/Data/Text/Show.hs, src/Data/Text/Unsafe.hs, tests/Tests/Properties/Basics.hs, tests/Tests/ShareEmpty.hs
Related to our discussion with @rhendric at https://discourse.haskell.org/t/the-quest-to-completely-eradicate-string-awkwardness/10111/75?u=bodigrim, let's implement `Data.Text.unpack` directly via `iterArray` instead of streaming / unstreaming. My immediate goal is to simplify dependencies between modules of `text`, but I imagine that performance could get better as well.
=> Implement Data.Text.unpack directly, without streaming

src/Data/Text.hs, src/Data/Text/Lazy.hs, tests/Tests/Properties/Instances.hs, text.cabal
It has never been easier. Ever since text is using UTF-8 encoding internally we don't have to go through the intermediate ByteString step. However, we keep deserialisation as is to ensure proper UTF-8'ness.
=> Serialise Texts without going through ByteString

src/Data/Text.hs, src/Data/Text/Internal/Lazy.hs, src/Data/Text/Lazy.hs
=> Implement pattern synonyms for StrictText and LazyText

.github/workflows/haskell-ci.yml, cabal.haskell-ci, text.cabal
`ghc-9.12` is not yet available in CI.
=> Bump dependencies (support ghc 9.12)

benchmarks/haskell/Benchmarks/Pure.hs, src/Data/Text/Lazy.hs, src/Data/Text/Show.hs
* Make Data.Text.unpack and Data.Text.Lazy.unpack good producers in list fusion. This allows them to fuse with good consumers of lists. Rewrite-back rules are included since the function bodies are large and we don't want to inline them if fusion doesn't occur.
* For Data.Text.Lazy, this change means that `unpack`, which uses `unstreamList`, no longer fuses with `streamList` under Text's stream fusion framework. This scenario seems very unlikely, since nothing else must be done to the list in between the two functions. Even `pack . unpack` does not satisfy this rule. So we are not losing anything valuable here.
* Add benchmarks for unpack, fusion and no fusion.
Closes #628.
---
Benchmarks with GHC 9.10.1
Before
<details>
<summary>Show</summary>
```
All
Pure
tiny
length . unpack
Text: …
```
=> Allow list fusion for Text and Text.Lazy unpack

benchmarks/haskell/Benchmarks/Pure.hs, src/Data/Text.hs, tests/Tests/Properties.hs, tests/Tests/Properties/CornerCases.hs, tests/Tests/Properties/Instances.hs, text.cabal
Resolve #288.
There are two commits here.
* Commit № 1 adds two new benchmarks in the `Pure` section: one for `sconcat` and one for `stimes`.
* Commit № 2 adds specialized implementation of `sconcat` and `stimes` to the instance of `Semigroup` for strict `Text`.
The benchmarks can be run like so:
```sh
first_commit_hash='180645e'
pattern='$2 == "Pure" && ($4 == "sconcat" || $4 == "stimes") && $5 != "LazyText"'
git checkout "$first_commit_hash" &&
cabal run text-benchmarks -- --pattern "$pattern" --timeout 10s --csv benchmarks.csv
git switch feature-sconcat-stimes &&
cabal run text-benchmarks -- --pattern "$pattern" --timeout 10s --baseline benchmarks.csv --fail-if-slower 110
```
This will take a few minutes. You should see better times almost everywhere — only the `tiny.sconcat` will show …
=> Feature: `sconcat` and `stimes`.

src/Data/Text/Internal/Encoding/Utf8.hs
The simple branching implementation is more efficient in the majority of use cases where the result is branched on anyway. In other cases, branch prediction should do a decent job on typical text.
Closes #630.
=> Change utf8LengthByLeader to a branching impl

.github/workflows/emulated.yml, benchmarks/haskell/Benchmarks.hs, tests/Tests/Regressions.hs, tests/Tests/Utils.hs, text.cabal
To avoid flooding the current directory with temp files when testing.
=> test: Use temporary to deal with temp files

src/Data/Text.hs, tests/Tests/Regressions.hs
=> Fix stimes for strict text when size wraps around Int

src/Data/Text/Lazy.hs, tests/Tests/Properties/Instances.hs
=> Define stimes 0 for lazy text

text.cabal
The MR includes two commits:
* the first merges the commit reachable from GHC's upstream 9.12 branch bumping `base` and `template-haskell` bounds for GHC 9.12.1.
* the second does the same for GHC 9.14
=> Support for GHC 9.12 and GHC 9.14

src/Data/Text/IO.hs
This PR adds detailed Haddock documentation for the `hGetChunk` function to clarify its behavior regarding UTF-8 character boundaries and buffer limitations.
The existing documentation didn't clearly explain why `hGetChunk` cannot guarantee reading an exact number of bytes. Users expecting byte-oriented behavior similar to `ByteString.hGetSome` may be confused by the character-oriented nature of Text operations.
- Added comprehensive Haddock documentation covering:
- UTF-8 character boundary handling (characters can be 1-4 bytes)
- Internal buffer limitation (2048 characters via `dEFAULT_CHAR_BUFFER_SIZE`)
- Clear distinction from byte-oriented operations
- Clarifies the non-configurable buffer size limitation
=> chore: Add comprehensive documentation for `hGetChunk` (#651)

src/Data/Text/Internal/Builder.hs
=> Shave off redundant field of Text.Internal.Buffer
