Data/Text/Lazy/Builder/Int.hs
This is @meteficha's suggestion that fixes https://github.com/bos/text/issues/114 and https://github.com/bos/aeson/issues/246. I have tested it locally.
=> Fix bug that caused encoding Int to loop forever.

Data/Text/Lazy.hs
I was making a `Data.Data` instance for a data type that has a `Data.Text.Lazy.Text` field, and noticed it was failing on `toConstr`, even though this worked for `Data.Text.Text`.
I then saw there was a disparity between the two instances, and assumed this was an oversight when the instance for `Data.Text.Text` was updated. So I went ahead and updated the `Data.Data` instance for `Data.Text.Lazy.Text` so that it behaves the same way as the instance for `Data.Text.Text`.
=> Add feature parity Data instance Text and Text.Lazy

Data/Text/Internal/Read.hs
=> Fix typo in module comment

Data/Text/Lazy/Builder/Int.hs, text.cabal
This basically reverts commit b806d9491c740dfcbf172d2936f1eeb3b72d3492.
and therefore resolve #138
=> Revert "Rename integer-simple to integer-pure (gh-138)"

Data/Text/Array.hs
Change 'qualifid' to 'qualified'
=> Fix minor typo

.gitignore
=> Fix GNUmakefile capitalization

tests-and-benchmarks.markdown, tests/Makefile
add a target for git and update docs
=> improve Makefile for getting test-data

Data/Text/Lazy/Builder/RealFloat.hs
=> Fix -incomplete-uni-patterns

Data/Text.hs
This pull request addresses #256.
=> Fixing broken link in documentation.

text.cabal
=> Bump template-haskell upper bound

.gitignore, benchmarks/python/cut.py, benchmarks/python/multilang.py, benchmarks/python/sort.py, benchmarks/python/strip_tags.py, benchmarks/python/utils.py
Python 2 is already sunset.
This patch upgrades existing scripts to Python 3.
=> Migrating scripts to Python 3.

.gitignore, benchmarks/text-benchmarks.cabal, cabal.tests.project, scripts/tests.sh, src/Data/Text/Encoding.hs, src/Data/Text/Internal/ByteStringCompat.hs, src/Data/Text/Internal/Encoding/Fusion.hs, src/Data/Text/Internal/Lazy/Encoding/Fusion.hs, tests/text-tests.cabal, text.cabal
This seems to compile. Not tested.
EDIT: I'd make a compat module for `mkBS` and `withBS`, so CPP don't need to be repeated.
Would be nice to test project from #293...
=> bytestring-0.11

text.cabal
See https://gitlab.haskell.org/ghc/ghc/issues/19083 and https://gitlab.haskell.org/ghc/ghc/-/merge_requests/5291.
=> Allow building with template-haskell-2.18.*

tests/Tests/Properties/Text.hs
Follow up to #274 
Also planning to
=> Add tests for elem

benchmarks/haskell/Benchmarks.hs, cbits/cbits.c, src/Data/Text/Array.hs, tests/Tests/Lift.hs, tests/Tests/Properties/Builder.hs, tests/Tests/Properties/LowLevel.hs, tests/Tests/Properties/Read.hs, tests/Tests/Properties/Substrings.hs, tests/Tests/Properties/Transcoding.hs, tests/Tests/QuickCheckUtils.hs, tests/Tests/Utils.hs, text.cabal
This is another omnibus of assorted changes, improving various aspects of tests, benchmarks and stuff. They are not specific to my WIP UTF8 branch, so it's easier to review and merge them separately.
=> Assorted fixes

src/Data/Text/IO.hs, src/Data/Text/Lazy/IO.hs
"Write a string the end of a file"
=> Fix `appendFile` haddock typos

src/Data/Text.hs, src/Data/Text/Internal/Fusion.hs, src/Data/Text/Internal/Fusion/Common.hs, src/Data/Text/Internal/Fusion/Types.hs
Adds some documentation for fusion modules. Note that this is all unchecked and I may have made some silly errors so I would appreciate someone scanning over for any obvious issues.
=> Add documentation for fusion modules.

.github/workflows/emulated.yml, .github/workflows/haskell-ci.yml, cbits/utils.c, src/Data/Text/Array.hs, tests/Tests/QuickCheckUtils.hs, text.cabal
It's important to run builds on a big-endian architecture.
=> Add s390x and ppc64le CI builds

src/Data/Text.hs, src/Data/Text/Internal/Fusion/Common.hs, src/Data/Text/Lazy.hs
See https://github.com/haskell/core-libraries-committee/issues/3
=> Future-proof imports for Eq

src/Data/Text/Internal/Lazy/Search.hs, src/Data/Text/Internal/Search.hs, tests/Tests/Properties/Text.hs
During testing of `pandoc` I found two issues with implementation of `indices`, see tests added.
=> Fix bugs in `indices`

src/Data/Text.hs, src/Data/Text/Internal/Fusion.hs, src/Data/Text/Internal/Fusion/Common.hs, src/Data/Text/Internal/Lazy/Fusion.hs, src/Data/Text/Lazy.hs
In line with https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6772/diffs and https://github.com/haskell/bytestring/pull/440.
=> Add HasCallStack

src/Data/Text/Encoding.hs
`aeson` benchmarks signalled (https://github.com/haskell/aeson/issues/893#issuecomment-986215880) that `encodeUtf8BuilderEscaped` got slower after UTF8 transition. This PR makes it 2-3x faster:
```
All
EncodeUtf8
non-ASCII
Text/encodeUtf8BuilderEscaped: OK (3.96s)
1.90 ms ±  53 μs, 46% faster than baseline
ASCII
Text/encodeUtf8BuilderEscaped: OK (10.32s)
629  μs ± 9.0 μs, 70% faster than baseline
```
=> Make encodeUtf8BuilderEscaped faster

.github/workflows/windows_and_macOS.yml, text.cabal
Fixes https://gitlab.haskell.org/ghc/ghc/-/issues/20878
CC @Mistuke
=> Fix static linking on Windows

.github/workflows/centos.yml, cbits/measure_off.c
Investigating https://gitlab.haskell.org/ghc/ghc/-/issues/21352
=> Add CentOS CI job

changelog.md, simdutf/simdutf.cpp, src/Data/Text/Internal/Fusion/Common.hs, src/Data/Text/Lazy.hs, tests/Tests/Properties/Transcoding.hs
changelog.md
simdutf/simdutf.cpp
src/Data/Text/Internal/Fusion/Common.hs
src/Data/Text/Lazy.hs
tests/Tests/Properties/Transcoding.hs
@Bodigrim missed these in `#414`
=> fix spelling errors

text.cabal
=> Bump ghc-prim upper bound

changelog.md
=> Clarify changelog on optimization of replicate

src/Data/Text.hs, src/Data/Text/Lazy.hs
=> doc: Refine complexity of compareLength

src/Data/Text.hs, src/Data/Text/Internal/Search.hs
=> doc: Fix URLs

text.cabal
Part of the proposal https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0475-tuple-syntax.rst
Tracked by https://gitlab.haskell.org/ghc/ghc/-/issues/21294
=> Bump the upper bound for ghc-prim

.cirrus.yml, text.cabal
(NetBSD issues has been filed as https://gitlab.haskell.org/ghc/ghc/-/issues/22577)
=> Add OpenBSD and NetBSD CI jobs

src/Data/Text.hs, src/Data/Text/Array.hs, src/Data/Text/Internal/Builder.hs, src/Data/Text/Internal/Encoding/Fusion.hs, src/Data/Text/Internal/Fusion/Common.hs, src/Data/Text/Internal/Lazy/Encoding/Fusion.hs, src/Data/Text/Internal/Private.hs, src/Data/Text/Lazy/Builder.hs
Rename Rank2Types to RankNTypes
=> Rename Rank2Types -> RankNTypes

src/Data/Text/Internal.hs
As discussed in https://github.com/haskell/text/issues/505#issuecomment-1433834556. Hopefully the last bit before release.
=> Make Data.Text.pack a lazy consumer of the input String

src/Data/Text/Internal/Encoding.hs, tests/Tests/Regressions.hs
=> Require bytestring-0.11.5 for UTF-8 validation

.github/workflows/haskell-ci.yml, changelog.md, text.cabal
@Lysxia once merged, would you like to upload onto Hackage?
=> Prepare `text-2.1` release

tests/Tests/Properties/Validate.hs
In the middle of writing and rewriting these tests I forgot to remove this comment.
=> tests: Remove outdated comment

src/Data/Text/Lazy/Read.hs, src/Data/Text/Read.hs, tests/Tests/Properties/Read.hs
=> Improve precision of Data.Text.Read.rational

.gitattributes
...otherwise GitHub classifies this project as C++ one :)
=> Exclude simdutf folder from language detection scan

.github/workflows/haskell-ci.yml, text.cabal
=> Update CI and drop job for GHC 8.2.2

src/Data/Text/Foreign.hs, tests/Tests/Properties/LowLevel.hs
=> Fix t_peek_cstring test

src/Data/Text/Encoding.hs
=> Add `@since` annotation to decodeUtf8Lenient

cbits/measure_off.c
=> Guard #define __STDC_NO_ATOMICS__ by #ifndef
